export const APPLICATION_SUBMIT_REQUEST = 'APPLICATION_SUBMIT_REQUEST';
export const APPLICATION_SUBMIT_SUCCESS = 'APPLICATION_SUBMIT_SUCCESS';
export const APPLICATION_SUBMIT_FAILURE = 'APPLICATION_SUBMIT_FAILURE';

export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST';
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
export const APPLICATION_LIST_FAILURE = 'APPLICATION_LIST_FAILURE';

export const APPLICATION_APPROVE_REQUEST = 'APPLICATION_APPROVE_REQUEST';
export const APPLICATION_APPROVE_SUCCESS = 'APPLICATION_APPROVE_SUCCESS';
export const APPLICATION_APPROVE_FAILURE = 'APPLICATION_APPROVE_FAILURE';

export const APPLICATION_DECLINE_REQUEST = 'APPLICATION_DECLINE_REQUEST';
export const APPLICATION_DECLINE_SUCCESS = 'APPLICATION_DECLINE_SUCCESS';
export const APPLICATION_DECLINE_FAILURE = 'APPLICATION_DECLINE_FAILURE';
