export const CHAT_MESSAGE_REQUEST = 'CHAT_MESSAGE_REQUEST';
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS';
export const CHAT_MESSAGE_FAILURE = 'CHAT_MESSAGE_FAILURE';

export const ADMIN_USERS_LIST_REQUEST = 'ADMIN_USERS_LIST_REQUEST';
export const ADMIN_USERS_LIST_SUCCESS = 'ADMIN_USERS_LIST_SUCCESS';
export const ADMIN_USERS_LIST_FAILURE = 'ADMIN_USERS_LIST_FAILURE';

export const ADMIN_APPLICATIONS_LIST_REQUEST = 'ADMIN_APPLICATIONS_LIST_REQUEST';
export const ADMIN_APPLICATIONS_LIST_SUCCESS = 'ADMIN_APPLICATIONS_LIST_SUCCESS';
export const ADMIN_APPLICATIONS_LIST_FAILURE = 'ADMIN_APPLICATIONS_LIST_FAILURE';
