export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAILURE = 'SERVICE_LIST_FAILURE';

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAILURE = 'SERVICE_DETAIL_FAILURE';

export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_FAILURE = 'SERVICE_CREATE_FAILURE';

export const SELLER_SERVICES_REQUEST = 'SELLER_SERVICES_REQUEST';
export const SELLER_SERVICES_SUCCESS = 'SELLER_SERVICES_SUCCESS';
export const SELLER_SERVICES_FAILURE = 'SELLER_SERVICES_FAILURE';
